DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS BRANDS;

CREATE TABLE BRANDS (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PRICES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    END_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CURR VARCHAR(3) NOT NULL,

    CONSTRAINT FK_PRICES_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID)
);

CREATE INDEX idx_price_lookup ON PRICES(BRAND_ID, PRODUCT_ID, START_DATE, END_DATE, PRIORITY);